[project]
name = "breastcancer"
version = "0.1.0"
requires-python = ">=3.10, <3.13"
dependencies = [
    "torch",
    "torchvision",
    "opencv-python",
    "pandas",
    "pillow",
    "scikit-learn",
    "tqdm",
    "matplotlib>=3.10.9",
    "seaborn>=0.13.2",
]

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu121" }
torchvision = { index = "pytorch-cu121" }
